import os
import time
import numpy as np
import torch
import torch.nn as nn
import torchvision.models as models
import torchvision.transforms as transforms
from PIL import Image
import tensorflow_datasets as tfds
import tensorflow as tf # Used for TFDS loading, ensure GPU is not grabbed if PyTorch is primary
from tqdm import tqdm
import h5py
import gc # Garbage collector

# --- Configuration ---
CNN_FEATURES_BASE_DIR = r"E:\CV_Features_CNN_PyTorch_Balanced" # Consider a new base dir for balanced features
CNN_MODEL_NAME = "AlexNet_Places365_PyTorch_FC_Features" # New name to reflect FC features
CNN_EXTRACTED_FEATURES_DIR = os.path.join(CNN_FEATURES_BASE_DIR, "cnn_extracted_features", CNN_MODEL_NAME)

# Path to the NPZ file generated by the BALANCED splitting script
# Make sure this matches the output of your create_balanced_split_and_labels()
NPZ_FILE_BALANCED_SPLIT = os.path.join(r"E:\CV_features", "train_test_splits_4cat_balanced", "train_test_split_data_4cat_balanced.npz")

TFDS_DATA_DIR = r"E:\CV_imgs" # Where TFDS stores dataset files

IMG_WIDTH, IMG_HEIGHT = 224, 224
BATCH_SIZE_PYTORCH_CNN = 32 # Adjust based on GPU memory
PLACES365_WEIGHTS_PATH = r"E:\CV_Features_CNN_PyTorch_Balanced\alexnet_places365.pth.tar" # Path to your .pth.tar file

# Move device definition outside functions so it's accessible globally
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")


# --- Custom PyTorch Dataset (Keep this outside the pipeline function) ---
class TFDSSubsetFeatureDataset(torch.utils.data.Dataset):
    def __init__(self, original_tfds_indices_list, image_numpy_list, broad_numeric_labels_list, transform=None):
        self.original_tfds_indices = original_tfds_indices_list # These are original TFDS indices
        self.images_numpy = image_numpy_list
        self.labels = broad_numeric_labels_list # These are numeric labels
        self.transform = transform
        if not (len(self.original_tfds_indices) == len(self.images_numpy) == len(self.labels)):
            raise ValueError("Indices, images, and labels lists must have the same length.")

    def __len__(self):
        return len(self.original_tfds_indices)

    def __getitem__(self, list_idx):
        original_tfds_idx_val = self.original_tfds_indices[list_idx]
        img_np = self.images_numpy[list_idx]
        label_val = self.labels[list_idx] # Should be numeric already
        try:
            image = Image.fromarray(img_np).convert('RGB')
        except Exception as e:
            print(f"\nERROR: Convert NumPy to PIL for original_tfds_idx {original_tfds_idx_val} (list_idx {list_idx}): {e}. Returning dummy image/data.")
            dummy_img = torch.zeros(3, IMG_HEIGHT, IMG_WIDTH, dtype=torch.float32)
            return original_tfds_idx_val, dummy_img, torch.tensor(label_val, dtype=torch.long) # Ensure label is tensor
        if self.transform:
            try:
                image = self.transform(image)
            except Exception as e:
                print(f"\nWARN: Transform error for original_tfds_idx {original_tfds_idx_val} (list_idx {list_idx}): {e}. Returning dummy image/data.")
                dummy_img = torch.zeros(3, IMG_HEIGHT, IMG_WIDTH, dtype=torch.float32)
                return original_tfds_idx_val, dummy_img, torch.tensor(label_val, dtype=torch.long)
        return original_tfds_idx_val, image, torch.tensor(label_val, dtype=torch.long)


# --- AlexNet Feature Extractor (Modified to extract from FC layers) ---
class AlexNetFcFeatureExtractor(nn.Module):
    def __init__(self, alexnet_model_places365):
        super().__init__()
        self.features_cnn = alexnet_model_places365.features
        self.avgpool = alexnet_model_places365.avgpool
        # We want the output of the second to last fully connected layer (before the final 365-class layer)
        # Original AlexNet classifier layers:
        # (0): Dropout(p=0.5)
        # (1): Linear(in_features=9216, out_features=4096)
        # (2): ReLU(inplace=True)
        # (3): Dropout(p=0.5)
        # (4): Linear(in_features=4096, out_features=4096)
        # (5): ReLU(inplace=True)
        # (6): Linear(in_features=4096, out_features=num_classes) -> This is what we modified for Places365 (365 classes)
        # We take up to layer (5) which outputs 4096 features
        self.classifier_head = nn.Sequential(*list(alexnet_model_places365.classifier.children())[:-1])

    def forward(self, x):
        x = self.features_cnn(x)
        x = self.avgpool(x)
        x = torch.flatten(x, 1)
        x = self.classifier_head(x) # Output will be (batch_size, 4096)
        return x

# --- Load Places365 Pretrained AlexNet Model (Modified to return feature extractor) ---
def load_alexnet_places365_fc_feature_extractor(weights_path):
    print(f"\nLoading AlexNet model architecture (PyTorch)...")
    try:
        model = models.alexnet(weights=None) # Or weights=models.AlexNet_Weights.DEFAULT for ImageNet if base needed
    except TypeError:
        model = models.alexnet(pretrained=False) # Fallback for older torchvision

    # Modify the final classifier layer for Places365 (365 classes)
    num_ftrs_original_classifier = model.classifier[6].in_features # Should be 4096
    model.classifier[6] = nn.Linear(num_ftrs_original_classifier, 365) # Places365 has 365 classes
    print("Adjusted AlexNet final classifier for 365 Places365 classes.")

    print(f"Loading Places365 weights from: {weights_path}")
    try:
        checkpoint = torch.load(weights_path, map_location=device)
        state_dict_from_checkpoint = None
        if isinstance(checkpoint, dict):
            if 'state_dict' in checkpoint:
                state_dict_from_checkpoint = checkpoint['state_dict']
            elif 'model' in checkpoint: # Common in some checkpoints
                state_dict_from_checkpoint = checkpoint['model']
            else:
                state_dict_from_checkpoint = checkpoint
        else:
            state_dict_from_checkpoint = checkpoint

        if state_dict_from_checkpoint is None:
            raise ValueError(f"Could not find state_dict in the loaded checkpoint from {weights_path}.")

        # --- FIX: Create a new state_dict with 'module.' prefix removed (if present) ---
        # This part of your code for fixing keys seems generally robust.
        new_state_dict = {}
        has_module_prefix = any('module.' in k for k in state_dict_from_checkpoint.keys())

        for k, v in state_dict_from_checkpoint.items():
            name = k
            if has_module_prefix and k.startswith('module.'): # A more general 'module.' removal
                name = k[7:] # remove `module.`
            elif 'features.module.' in k: # Specific to your previous observation
                name = k.replace('features.module.', 'features.')
            # Add other potential prefix issues if they arise
            new_state_dict[name] = v
        
        model.load_state_dict(new_state_dict, strict=True) # Set strict=True to catch mismatches
        print("Successfully loaded Places365 weights into full AlexNet model.")

    except FileNotFoundError:
        print(f"ERROR: Places365 weights file not found at {weights_path}. Please check the path.")
        exit()
    except Exception as e:
        print(f"ERROR loading Places365 weights: {e}")
        print("Ensure the weights file corresponds to an AlexNet model with a final layer for 365 classes.")
        # You can add debug prints for model keys vs checkpoint keys here if needed
        exit()

    # Create the feature extractor using the FC layers
    feature_extractor = AlexNetFcFeatureExtractor(model)

    # Freeze all parameters in the feature extractor
    for param in feature_extractor.parameters():
        param.requires_grad = False
    feature_extractor.eval() # Set to evaluation mode

    print("AlexNet FC feature extractor (up to penultimate FC layer) ready, weights frozen.")
    return feature_extractor.to(device)


# --- Define Preprocessing Transform (Keep this outside the pipeline function) ---
def get_alexnet_preprocessing_transform():
    print(f"\nDefining preprocessing transform for AlexNet ({IMG_HEIGHT}x{IMG_WIDTH} input)...")
    transform = transforms.Compose([
        transforms.Resize(256),
        transforms.CenterCrop(IMG_HEIGHT), # AlexNet standard input size
        transforms.ToTensor(),
        transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]) # ImageNet stats commonly used
    ])
    print("AlexNet preprocessing transform defined.")
    return transform


# --- Feature Extraction Loop and Saving (Keep this outside the pipeline function) ---
def extract_and_save_features(
    original_tfds_indices_for_dataset, images_numpy_for_dataset, broad_numeric_labels_for_dataset,
    model_obj, transform_obj, output_filepath):

    print(f"\nPreparing dataset for {os.path.basename(output_filepath)} with {len(images_numpy_for_dataset)} images.")
    # Pass numeric labels directly
    dataset = TFDSSubsetFeatureDataset(original_tfds_indices_for_dataset, images_numpy_for_dataset,
                                       broad_numeric_labels_for_dataset, transform=transform_obj)

    # Consider num_workers > 0 if I/O is a bottleneck and not causing issues with TFDS/PIL
    dataloader = torch.utils.data.DataLoader(dataset, batch_size=BATCH_SIZE_PYTORCH_CNN,
                                             shuffle=False, num_workers=0, pin_memory=True if device.type == 'cuda' else False)

    features_list, actual_indices_processed, actual_labels_processed = [], [], []
    print(f"Extracting features for {len(dataset)} images using {CNN_MODEL_NAME}...")
    model_obj.eval() # Ensure model is in evaluation mode

    dataloader_tqdm = tqdm(dataloader, desc=f"Extracting {CNN_MODEL_NAME} Features", leave=True)
    with torch.no_grad():
        for original_tfds_indices_batch, images_batch, numeric_labels_batch in dataloader_tqdm:
            # Basic check for dummy/malformed batches from dataset __getitem__
            if images_batch.ndim != 4 or images_batch.shape[1] != 3 or \
               (torch.all(images_batch == 0) and images_batch.shape[0] > 0):
                dataloader_tqdm.write(f"Skipping a potentially malformed or dummy batch. Original TFDS indices: {original_tfds_indices_batch.tolist()}")
                continue

            images_batch = images_batch.to(device)
            # numeric_labels_batch are already tensors from the dataset

            try:
                features_batch = model_obj(images_batch) # Shape: (batch_size, 4096)
                # No additional flattening needed if model_obj is AlexNetFcFeatureExtractor

                features_list.extend(features_batch.cpu().numpy())
                actual_indices_processed.extend(original_tfds_indices_batch.cpu().tolist())
                actual_labels_processed.extend(numeric_labels_batch.cpu().tolist()) # Labels are already numeric

            except Exception as e:
                dataloader_tqdm.write(f"ERROR processing batch (original TFDS indices {original_tfds_indices_batch.tolist()}): {e}. Skipping batch.")
                # import traceback; traceback.print_exc() # For detailed error
                continue

    if features_list:
        features_array = np.array(features_list, dtype=np.float32)
        indices_array = np.array(actual_indices_processed, dtype=np.int32) # Original TFDS indices
        labels_array = np.array(actual_labels_processed, dtype=np.int8)   # Numeric broad labels

        print(f"\nSaving extracted data to {output_filepath}...")
        try:
            os.makedirs(os.path.dirname(output_filepath), exist_ok=True)
            with h5py.File(output_filepath, 'w') as hf:
                hf.create_dataset('features', data=features_array, compression="gzip")
                hf.create_dataset('original_tfds_indices', data=indices_array) # Save original TFDS indices
                hf.create_dataset('labels_numeric', data=labels_array) # Save numeric labels
            print(f"Saved: {output_filepath}")
            print(f"  Features shape: {features_array.shape}")
            print(f"  Original TFDS Indices shape: {indices_array.shape}")
            print(f"  Numeric Labels shape: {labels_array.shape}")

            if features_array.shape[0] != len(images_numpy_for_dataset):
                print(f"WARN: Number of saved features ({features_array.shape[0]}) is less than the number of images provided to the dataset ({len(images_numpy_for_dataset)}). This may be due to errors during processing.")

        except Exception as e:
            print(f"ERROR saving HDF5 file {output_filepath}: {e}")
    else:
        print(f"No features were successfully extracted for {os.path.basename(output_filepath)}. No file saved.")


# --- Main Execution Pipeline (All data loading/prep moves HERE) ---
def extract_alexnet_places365_features_pipeline():
    if torch.cuda.is_available():
        print(f"PyTorch using GPU: {torch.cuda.get_device_name(0)}")
    else:
        print("PyTorch using CPU.")

    os.makedirs(CNN_EXTRACTED_FEATURES_DIR, exist_ok=True)
    print(f"Saving extracted features to: {CNN_EXTRACTED_FEATURES_DIR}")

    # --- 1. Load TFDS Dataset Definition (Original Train Split, Enumerated) ---
    print("\n--- Defining TFDS Data Source (Original Train Split) ---")
    # Prevent TensorFlow from grabbing all GPU memory if PyTorch is also using it
    # tf.config.experimental.set_visible_devices([], 'GPU') # Might be too restrictive
    gpus = tf.config.experimental.list_physical_devices('GPU')
    if gpus:
        try:
            # Restrict TensorFlow to only allocate a small fraction of memory e.g. 1GB
            # Or, prevent it from allocating any if PyTorch needs it all.
            # For this script, TFDS is just for data loading, not heavy computation.
            tf.config.experimental.set_memory_growth(gpus[0], True)
            # Alternatively, if TF is only for CPU loading:
            # tf.config.set_visible_devices([], 'GPU')
            print("Configured TensorFlow GPU memory growth or visibility.")
        except RuntimeError as e:
            print(f"Error setting TF GPU options: {e}")

    ds_info_obj = tfds.builder('places365_small', data_dir=TFDS_DATA_DIR).info
    num_total_train_images = ds_info_obj.splits['train'].num_examples
    print(f"Total images in Places365 'train' split: {num_total_train_images}")

    full_ds_train_tfds = tfds.load(
        'places365_small',
        split='train',
        data_dir=TFDS_DATA_DIR,
        shuffle_files=False, # CRITICAL: Must be False for consistent original_tfds_idx
    )
    ds_train_enumerated_tfds = full_ds_train_tfds.enumerate() # (original_tfds_idx, item)

    # --- 2. Load Train/Test Split Original TFDS Indices and Numeric Broad Labels from NPZ ---
    print(f"Loading BALANCED train/test split data (ORIGINAL TFDS indices and broad labels) from: {NPZ_FILE_BALANCED_SPLIT}")
    if not os.path.exists(NPZ_FILE_BALANCED_SPLIT):
        print(f"ERROR: NPZ file for balanced split not found at {NPZ_FILE_BALANCED_SPLIT}.")
        print("Please ensure the `create_balanced_split_and_labels()` script has been run successfully.")
        exit()
    try:
        split_data_npz = np.load(NPZ_FILE_BALANCED_SPLIT)
        # These are ORIGINAL TFDS indices from the balanced split NPZ
        original_tfds_train_indices_npz = split_data_npz['train_indices'].tolist()
        original_tfds_test_indices_npz = split_data_npz['test_indices'].tolist()
        # These are NUMERIC broad labels from the balanced split NPZ
        y_train_numeric_broad_npz = split_data_npz['train_labels_numeric'].tolist()
        y_test_numeric_broad_npz = split_data_npz['test_labels_numeric'].tolist()

        print(f"Loaded {len(original_tfds_train_indices_npz)} train original TFDS indices/labels and "
              f"{len(original_tfds_test_indices_npz)} test original TFDS indices/labels from NPZ.")
        if not (len(original_tfds_train_indices_npz) == len(y_train_numeric_broad_npz) and \
                len(original_tfds_test_indices_npz) == len(y_test_numeric_broad_npz)):
            print("ERROR: Mismatch between number of indices and labels in NPZ. Halting.")
            exit()
    except Exception as e:
        print(f"An unexpected error occurred loading NPZ: {e}")
        exit()

    # --- 3. Cache ONLY the REQUIRED Images from TFDS based on Original TFDS Indices ---
    all_required_original_tfds_indices_set = set(original_tfds_train_indices_npz + original_tfds_test_indices_npz)
    print(f"Identified {len(all_required_original_tfds_indices_set)} unique ORIGINAL TFDS indices required from NPZ splits.")

    print(f"Caching ONLY the {len(all_required_original_tfds_indices_set)} required images by iterating original TFDS 'train' split...")
    # This map will store: original_tfds_idx -> {'image': image_numpy, 'label_numeric': label_from_npz}
    required_data_map = {}

    # Create maps from NPZ data for quick lookup of labels during caching for verification (optional but good)
    npz_idx_to_label_map = {idx: lbl for idx, lbl in zip(original_tfds_train_indices_npz, y_train_numeric_broad_npz)}
    npz_idx_to_label_map.update({idx: lbl for idx, lbl in zip(original_tfds_test_indices_npz, y_test_numeric_broad_npz)})

    num_found_in_tfds = 0
    # Iterate through the enumerated *original* TFDS train split
    for original_tfds_idx_tensor, item_tfds in tqdm(ds_train_enumerated_tfds.as_numpy_iterator(),
                                             total=num_total_train_images,
                                             desc="Filtering/Caching TFDS images by original index"):
        current_original_tfds_idx = int(original_tfds_idx_tensor)

        if current_original_tfds_idx in all_required_original_tfds_indices_set:
            required_data_map[current_original_tfds_idx] = {
                'image': item_tfds['image'],
                'label_numeric': npz_idx_to_label_map[current_original_tfds_idx] # Get label from NPZ for consistency
            }
            num_found_in_tfds += 1
            if num_found_in_tfds == len(all_required_original_tfds_indices_set):
                print(f"\nAll {num_found_in_tfds} required images have been found and cached. Breaking TFDS iteration.")
                break
    print(f"Cached {len(required_data_map)} images (and their numeric labels from NPZ) from TFDS.")

    if num_found_in_tfds < len(all_required_original_tfds_indices_set):
        missing_count = len(all_required_original_tfds_indices_set) - num_found_in_tfds
        print(f"WARNING: Only found {num_found_in_tfds} out of {len(all_required_original_tfds_indices_set)} required images ({missing_count} missing). "
              "This means some original_tfds_indices from your NPZ file were not encountered in the TFDS 'train' scan. "
              "Ensure NPZ indices are valid and within the range of the TFDS 'train' split size.")
        # You might want to list some missing indices for debugging if this happens frequently.

    # --- 4. Prepare Data Lists for PyTorch Dataset ---
    # Training set
    images_train_actual_numpy = []
    y_train_actual_numeric_broad = [] # Numeric labels
    actual_train_original_tfds_indices_list = []

    for original_idx in original_tfds_train_indices_npz:
        if original_idx in required_data_map:
            data_entry = required_data_map[original_idx]
            images_train_actual_numpy.append(data_entry['image'])
            y_train_actual_numeric_broad.append(data_entry['label_numeric'])
            actual_train_original_tfds_indices_list.append(original_idx)
        else:
            print(f"Warning: Train original_tfds_idx {original_idx} from NPZ not found in cached TFDS data. Skipping.")

    # Testing set
    images_test_actual_numpy = []
    y_test_actual_numeric_broad = []
    actual_test_original_tfds_indices_list = []

    for original_idx in original_tfds_test_indices_npz:
        if original_idx in required_data_map:
            data_entry = required_data_map[original_idx]
            images_test_actual_numpy.append(data_entry['image'])
            y_test_actual_numeric_broad.append(data_entry['label_numeric'])
            actual_test_original_tfds_indices_list.append(original_idx)
        else:
            print(f"Warning: Test original_tfds_idx {original_idx} from NPZ not found in cached TFDS data. Skipping.")

    print(f"Prepared {len(images_train_actual_numpy)} images for training.")
    print(f"Prepared {len(images_test_actual_numpy)} images for testing.")

    if not images_train_actual_numpy or not images_test_actual_numpy:
        print("ERROR: No valid images found for train or test after filtering. Cannot proceed.")
        exit()

    # Clean up large cache map
    del required_data_map
    gc.collect()
    print("Cleaned up intermediate image/label cache map.")

    # --- 5. Load Model and Preprocessing Transform ---
    feature_extractor_model = load_alexnet_places365_fc_feature_extractor(PLACES365_WEIGHTS_PATH)
    preprocessing_transform = get_alexnet_preprocessing_transform()

    # Output file suffix should reflect the balanced nature and feature type
    # The TARGET_IMAGES_PER_BROAD_CATEGORY is not directly available here unless passed or inferred from NPZ filename.
    # For simplicity, use a generic "balanced" suffix or extract from NPZ filename if it's encoded there.
    output_file_suffix = "balanced_fc_features" # Example suffix

    # --- 6. Process Training Set ---
    train_output_filepath = os.path.join(CNN_EXTRACTED_FEATURES_DIR, f'X_train_{CNN_MODEL_NAME.lower()}_{output_file_suffix}.h5')
    extract_and_save_features(
        actual_train_original_tfds_indices_list,
        images_train_actual_numpy,
        y_train_actual_numeric_broad, # Pass numeric labels
        feature_extractor_model,
        preprocessing_transform,
        train_output_filepath
    )

    del images_train_actual_numpy, y_train_actual_numeric_broad, actual_train_original_tfds_indices_list
    gc.collect()
    print("Cleaned up training data from RAM.")

    # --- 7. Process Testing Set ---
    test_output_filepath = os.path.join(CNN_EXTRACTED_FEATURES_DIR, f'X_test_{CNN_MODEL_NAME.lower()}_{output_file_suffix}.h5')
    extract_and_save_features(
        actual_test_original_tfds_indices_list,
        images_test_actual_numpy,
        y_test_actual_numeric_broad, # Pass numeric labels
        feature_extractor_model,
        preprocessing_transform,
        test_output_filepath
    )

    del images_test_actual_numpy, y_test_actual_numeric_broad, actual_test_original_tfds_indices_list
    gc.collect()
    print("Cleaned up testing data from RAM.")

    print(f"\n--- PyTorch CNN FC Feature Extraction Pipeline Complete ({CNN_MODEL_NAME}) ---")